language: node_js
node_js:
    - '4'
    - '6'
    - 'node'
deploy:
  provider: npm
  email: cosmosgenius@gmail.com
  api_key:
    secure: KCjObD7wkYT+iYYYQbN1dJ1mak1MLkYg/CHE1ECGZfgeA3rGfl+w0/ZZvV4gy3njaXALfXJwCd3bFh49fTRMjhbnXSFozJG7Zu6NPtnBeqPMeWB3AcwKOrtBpsJne3gkQUCQZZVEIbsaG4Xbqw03KUuqH2xBgwLmfMoYnTWmnOg=
  on:
    tags: true
    repo: cosmosgenius/simple-bodyparser
    branch: master
after_success:
    - bash <(curl -s https://codecov.io/bash)
